### ISSUE TITLE
Timer reset

### ISSUE THREAD

**Issue by milan-vidakovic-work** [alhardy/AppMetrics#128]
Greetings alhardy,

First of all - top stuff. 

Are there plans to add ResetOnReporting property for timers (similar to counters)? If not, what would be the way to mimic the same behaviour by using the Reset method?

**Comment by alhardy** [comment]
@milan-vidakovic-work  Thanks for the good feedback 👍 

A `Timer` exposes a count using the count measured by it's `Meter`.

I looked at this when adding the option to reset a `Counter` on reporting, currently if we were to reset a `Meter` on reporting it would also reset the rates which we wouldn't want, if there was an option to reset just the count this would still have an effect on the rates as it's used in the moving average calculation.

I guess there could be an additional count property on a `Meter` which is allowed to be reset and is the count used when flushing metrics. I'll have to think about it some more, but potentially it could be added.

**Comment by milan-vidakovic-work** [comment]
Thank you very much for your prompt response. 

The question came from a requirement to measure a timer aggregate (over report interval duration), without having values from previous report submissions linger on (and accumulate). I'm sure there is a workaround, but wanted to know if that's something you timer might support as well.

**Comment by alhardy** [comment]
@milan-vidakovic-work could you clarify if you were refering to resetting the count exposed on a timer or wanting to reset all a timers values? If you're after a total duration you could just sum the `lastValue`s.

I'm likely to remove reporting the count from meters (and therefore timers) as it's not very useful and only exists for internal calculations, the counter metric type exists to count things.

**Comment by milan-vidakovic-work** [comment]
@alhardy I was referring to resetting timer values altogether. To clarify, if you've ever used statsd, you know that all aggregated data are being reset after a submission (apart from gauges).  We are using a custom metrics server, so I would need a clean slate after every report is sent - meaning, reports should contain only data relevant to the current reporting period. I can understand if this is too specific of a request.

**Comment by alhardy** [comment]
@milan-vidakovic-work ah OK, yes this is possible, you would have to create a wrapper around the `ReportRunner` and implement your own [`ReportTimer` method](https://github.com/alhardy/AppMetrics/blob/dev/src/App.Metrics/Reporting/ReportRunner%7BT%7D.cs#L187). When getting the timer value you want `valueSource.ValueProvider.GetValue(true);` to reset the underlying meter, histogram and counter, see [here](https://github.com/alhardy/AppMetrics/blob/dev/src/App.Metrics/Timer/DefaultTimerMetric.cs#L110).

Otherwise, I'm happy to take a PR providing the reset flag on metric options as implemented for [counters](https://github.com/alhardy/AppMetrics/blob/dev/src/App.Metrics/Reporting/PackMetricValueSourceExtensions.cs#L68)

**Comment by EgorManevich** [comment]
Hi,

Any progress on this? 
`ResetOnReporting` for `Meter`, `Histogram` and `Timer` would be very helpful. Unfortunately now I have to add counter every time I need to display rate.
I tried using InfluxDb's `non_negative_difference` function on cumulative `count`, but it throws away those points that are reported after server reset. 

Thanks.
