### ISSUE TITLE
Extract App.Metrics.Abstractions to independent package

### ISSUE THREAD

**Issue by petriashev** [alhardy/AppMetrics#134]
Problem:
package App.Metrics has many dependensies: Microsoft.Extensions.Configuration.Abstractions, Microsoft.Extensions.Logging.Abstractions and so on...
When I want to use IMetrics injected to my services I need many dependencies.

Is is possible to extract base interfaces to other package (App.Metrics.Abstractions)?

**Comment by alhardy** [comment]
@petriashev There are currently four Microsoft Extension type dependencies, two of which are abstractions themselves the others are System type assemblies.

Rather than an `App.Metrics.Abstractions` package I might look at a DI / Startup package instead which should remove the majority of dependencies on `App.Metrics` Core which should resolve your "problem".

**Comment by alhardy** [comment]
This will require breaking changes, holding this issue for when AppMetrics supports AspNet Core 2.0 a major version bump can be done then.

**Comment by petriashev** [comment]
Is this work in your roadmap?

**Comment by alhardy** [comment]
Yes, can't give you a date though, can say probably within a month of ASP.NET Core 2.0 having a stable release.
