### ISSUE TITLE
.NET4.5.2 not support App.Metrics.Formatters.Json?

### ISSUE THREAD

**Issue by l2999019** [alhardy/AppMetrics#177]
.NET4.5.2 not support App.Metrics.Formatters.Json v1.2?
emmm...
Nuget The above shows only support for .NET4.6.1

https://www.nuget.org/packages/App.Metrics.Formatters.Json/

**Comment by alhardy** [comment]
At the moment `App.Metrics.Formatters.Json` as a dependency on AppMetrics middleware which in turn has a dependency on AspNetCore which won't run on .NET452. A while back I wrote https://github.com/alhardy/AppMetrics.Owin also supporting WebApi and MVC but haven't kept it up-to-date due to there not being much adoption. Would you be interested in getting that repo up to date?

**Comment by l2999019** [comment]
Do you mean I could join in and help update it?

**Comment by alhardy** [comment]
I mean submit a PR on [AppMetrics.Owin](https://github.com/alhardy/AppMetrics.Owin) ;) At the moment I'm concentrating on the next release of AppMetrics and don't have a need myself or enough interest to work on the Owin part of it.

**Comment by viswa-lakshmi** [comment]
Is AppMetrics.Owin maitained? I would like to export Prometheus client metrics in json format. Is there a way to do this?
