### ISSUE TITLE
HealthChecks class in website assembly not detected

### ISSUE THREAD

**Issue by MaitreDede** [alhardy/AppMetrics#73]
Hi,

I don't know if it is a wanted behavior or not. The `HealthCheck` defined in the web application are not found when adding healthchecks.
Version of AppMetrics : 1.0.0-beta4
Steps to reproduce : 
- Create a new Solution
- Add a new dotnet core library project,  with a HealthCheck class labeled "lib"
- Add a new dotnet core asp.net project, with basic appmetrics configuration (like the mvc.sample project)
- Add reference to previous lib project
- Add new HealthCheck class labeled "web".
- Run
When looking at /health, we can see only the "lib" healthcheck, not the "web" one.

**Comment by alhardy** [comment]
Thanks for identifing this. This issue has been fixed in 1.0.0-beta5, tested using the [latest samples](https://github.com/alhardy/AppMetrics.Samples/tree/dev/src/Mvc.Sample).

I'll be releasing 1.0.0-beta5 sometime this week, otherwise you can try the dev build on [myget](https://www.myget.org/feed/alhardy/package/nuget/App.Metrics.Extensions.Mvc)
